# RiskAlert Mining Dataset — Stage 2 Vehicle + PPE Detection
# Source:  Roboflow Universe — personal-q02wc/riskalert-mining v1
# Images:  712 total | 498 train / 142 valid / 72 test
# License: MIT

path: /Users/nanolescuras/SmartMine-Vision-AI/datasets/raw/vehicles/riskalert
train: train/images
val:   valid/images
test:  test/images

nc: 34
names:
  0:  ANIMAL
  1:  CAMIONETA
  2:  CARGADOR_FRONTAL
  3:  CISTERNA_AGUA
  4:  CONOS_DELIMITADORES
  5:  EXCAVADORA
  6:  MINIBUS
  7:  MOTONIVELADORA
  8:  PERSONA
  9:  PERSONA_CON_CASCO
  10: PERSONA_CON_GUANTES
  11: PERSONA_CON_LENTES
  12: PERSONA_CON_RESPIRADOR
  13: PERSONA_ROPA_CINTA_REFLECTIVA
  14: PERSONA_SIN_CASCO
  15: PERSONA_SIN_CHALECO
  16: PERSONA_SIN_GUANTES
  17: PERSONA_SIN_LENTES
  18: PERSONA_SIN_RESPIRADOR
  19: PERSONA_SIN_ROPA_CINTA_REFLECTIVA
  20: POLVO
  21: RETRO_EXCAVADORA
  22: RODILLO
  23: SENALIZACION
  24: TRACTOR
  25: VIA_BUEN_ESTADO
  26: VIA_CON_MURO_SEGURIDAD
  27: VIA_EN_MAL_ESTADO
  28: VIA_NO_REGADA
  29: VIA_OBSTACULIZADA
  30: VIA_SATURADA
  31: VIA_SENALIZADA
  32: VIA_SIN_MURO_SEGURIDAD
  33: VOLQUETE

# Vehicle classes (Module 2 primary targets)
vehicle_classes: [1, 2, 3, 5, 6, 7, 21, 22, 24, 33]

# PPE compliance classes (complement Module 1)
ppe_compliant:    [9, 10, 11, 12, 13]
ppe_violation:    [14, 15, 16, 17, 18, 19]
person_class:     [8]
