path: ../../datasets/merged/smartmine_v1
train: train/images
val: valid/images
test: test/images
nc: 33
names:
- person
- person_con_casco
- person_sin_casco
- person_con_chaleco
- person_sin_chaleco
- person_con_guantes
- person_sin_guantes
- person_con_lentes
- person_sin_lentes
- person_con_respirador
- person_sin_respirador
- person_ropa_reflectiva
- person_sin_ropa_reflectiva
- mask
- camioneta
- minibus
- volquete
- camion
- excavadora
- retro_excavadora
- cargador_frontal
- motoniveladora
- tractor
- rodillo
- cisterna_agua
- safety_cone
- senalizacion
- hardhat
- safety_vest
- animal
- polvo
- machinery
- vehiculo_generico
